/* eslint-disable import/prefer-default-export */

export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';

export const FETCH_YOUTUBE_LIST = 'FETCH_YOUTUBE_LIST';
export const FETCH_YOUTUBE_LIST_START = 'FETCH_YOUTUBE_LIST_START';
export const FETCH_YOUTUBE_LIST_RESULTS = 'FETCH_YOUTUBE_LIST_RESULTS';
export const FETCH_YOUTUBE_LIST_ERROR = 'FETCH_YOUTUBE_LIST_ERROR';
export const SELECT_YOUTUBE_VIDEO = 'SELECT_YOUTUBE_VIDEO'
export const FILTER_TOP_LEVEL_PLAYER = 'FILTER_TOP_LEVEL_PLAYER'
export const FILTER_LOWER_LEVEL_PLAYER = 'FILTER_LOWER_LEVEL_PLAYER'
export const SELECT_DRAFT_PLAYER = 'SELECT_DRAFT_PLAYER'
