// From CBS.com NFL Draft page
// copied table into TSV -> JSON converter
 //
const HEROES = [
  {
    "name": 'Tulen',
    'alt_names': ['Tulen'],
    "nickname": 'Pure',
    "classes": ['mage'],
    'lanes': ['mid', 'jungle', 'roam'],
    'roles': ['finisher', 'harass'],
    'tier': 's',
    'tier_index': 2,
    "folder": 'tulen'
  },
  {
    "name": 'Airi',
    'alt_names': ['Airi'],
    "nickname": 'Kunoichi',
    "classes": ['warrior', 'assassin'],
    'lanes': ['solo', 'ds', 'jungle'],
    'roles': ['mobility'],
    'tier': 'a',
    'tier_index': 3,
    "folder": 'airi'
  },
  {
    "name": 'Aleister',
    'alt_names': ['Aleister'],
    "nickname": 'Lord of Mischief',
    "classes": ['mage'],
    'lanes': ['support', 'roam'],
    'roles': ['control'],
    'tier': 'c',
    'tier_index': 5,
    "folder": 'aleister'
  },
  {
    "name": 'Alice',
    'alt_names': ['Alice'],
    "nickname": 'Adorable Mystic',
    "classes": ['support'],
    'lanes': ['support', 'roam'],
    'roles': ['control', 'buffs'],
    'tier': 'b',
    'tier_index': 4,
    "folder": 'alice'
  },
  {
    "name": 'Arduin',
    'alt_names': ['Arduin'],
    "nickname": 'Spirit',
    "classes": ['warrior', 'tank'],
    'lanes': ['ds', 'solo', 'roam'],
    'roles': ['mobility', 'control'],
    'tier': 'c',
    'tier_index': 5,
    "folder": 'arduin'
  },
  {
    "name": 'Arthur',
    'alt_names': ['Arthur'],
    "nickname": 'Chosen',
    "classes": ['warrior', 'tank'],
    'lanes': ['ds', 'solo', 'roam'],
    'roles': ['initiator', 'mobility'],
    'tier': 'a',
    'tier_index': 3,
    "folder": 'arthur'
  },
  {
    "name": 'Astrid',
    'alt_names': ['Astrid'],
    "nickname": 'Indomitable',
    "classes": ['warrior', 'tank'],
    'lanes': ['ds', 'solo', 'roam'],
    'roles': ['initiator'],
    'tier': 'a',
    'tier_index': 3,
    "folder": 'astrid'
  },
  {
    "name": "Azzen'Ka",
    'alt_names': ["Azzen'Ka", 'azzenka', 'azzen'],
    "nickname": 'Forgotten',
    "classes": ['mage'],
    'lanes': ['damage', 'roam'],
    'roles': ['control'],
    'tier': 'c',
    'tier_index': 5,
    "folder": 'azzenka'
  },
  {
    "name": 'Batman',
    'alt_names': ['Batman'],
    "nickname": 'Dark Knight',
    "classes": ['assassin'],
    'lanes': ['jungle', 'roam'],
    'roles': ['mobility'],
    'tier': 'a',
    'tier_index': 3,
    "folder": 'batman',
    "regions": ['na', 'eu']
  },
  {
    "name": 'Butterfly',
    'alt_names': ['Butterfly', 'bf', 'butter'],
    "nickname": "Death's Whisper",
    "classes": ['assassin', 'warrior'],
    'lanes': ['jungle'],
    'roles': ['mobility', 'finisher'],
    'tier': 'b',
    'tier_index': 4,
    "folder": 'butterfly'
  },
  {
    "name": 'Chaugnar',
    'alt_names': ['Chaugnar', 'chaug'],
    "nickname": 'Herald of the Void',
    "classes": ['support', 'tank'],
    'lanes': ['support', 'roam'],
    'roles': ['buffs'],
    'tier': 's',
    'tier_index': 2,
    "folder": 'chaugnar'
  },
  {
    "name": 'Cresht',
    'alt_names': ['Cresht'],
    "nickname": 'Mermidon',
    "classes": ['tank', 'support'],
    'lanes': ['ds', 'solo', 'support'],
    'roles': ['control'],
    'tier': 'a',
    'tier_index': 3,
    "folder": 'cresht'
  },
  {
    "name": 'Diaochan',
    'alt_names': ['Diaochan', 'diao'],
    "nickname": 'Crystal Lotus',
    "classes": ['Mage'],
    'lanes': ['damage', 'roam', 'support'],
    'roles': ['control'],
    'tier': 'c',
    'tier_index': 5,
    "folder": 'diaochan'
  },
  {
    "name": 'Fennik',
    'alt_names': ['Fennik'],
    "nickname": 'Vulpis Ignis',
    "classes": ['marksman'],
    'lanes': ['damage', 'jungle'],
    'roles': ['mobility'],
    'tier': 'b',
    'tier_index': 4,
    "folder": 'fennik'
  },
  {
    "name": 'Gildur',
    'alt_names': ['Gildur'],
    "nickname": 'Gilded',
    "classes": ['tank'],
    'lanes': ['damage', 'roam'],
    'roles': ['mobility'],
    'tier': 'c',
    'tier_index': 5,
    "folder": 'gildur'
  },
  {
    "name": 'Grakk',
    'alt_names': ['Grakk', 'grak'],
    "nickname": 'Glutton',
    "classes": ['tank', 'mage'],
    'lanes': ['support', 'roam'],
    'roles': ['control'],
    'tier': 'c',
    'tier_index': 5,
    "folder": 'grakk'
  },
  {
    "name": 'Ignis',
    'alt_names': ['Ignis'],
    "nickname": 'Anointed One',
    "classes": ['mage'],
    'lanes': ['roam', 'mid'],
    'roles': ['harass'],
    'tier': 'c',
    'tier_index': 5,
    "folder": 'ignis'
  },
  {
    "name": 'Ilumia',
    'alt_names': ['Ilumia', 'illumia'],
    "nickname": 'Seer',
    "classes": ['mage'],
    'lanes': ['damage', 'roam'],
    'roles': ['control', 'harass'],
    'tier': 'c',
    'tier_index': 5,
    "folder": 'ilumia'
  },
  {
    "name": 'Jinnar',
    'alt_names': ['Jinnar'],
    "nickname": 'Incorruptible',
    "classes": ['mage'],
    'lanes': ['roam', 'mid'],
    'roles': ['harass'],
    'tier': 'a',
    'tier_index': 3,
    "folder": 'jinnar'
  },
  {
    "name": 'Kahlii',
    'alt_names': ['Kahlii'],
    "nickname": 'Ghost Guardian',
    "classes": ['mage'],
    'lanes': ['mid', 'roam'],
    'roles': ['harass'],
    'tier': 'b',
    'tier_index': 4,
    "folder": 'kahlii'
  },
  {
    "name": "Kil'Groth",
    'alt_names': ["Kil'Groth", 'kill', 'kilgroth', 'kil'],
    "nickname": 'Terror',
    "classes": ['warrior'],
    'lanes': ['ds', 'jungle'],
    'roles': ['mobility'],
    'tier': 'a',
    'tier_index': 3,
    "folder": 'kilgroth'
  },
  {
    "name": 'Kriknak',
    'alt_names': ['Kriknak', 'krik'],
    "nickname": 'Scarabin',
    "classes": ['warrior'],
    'lanes': ['jungle', 'roam'],
    'roles': ['mobility'],
    'tier': 'b',
    'tier_index': 4,
    "folder": 'kriknak'
  },
  {
    "name": 'Krixi',
    'alt_names': ['Krixi'],
    "nickname": 'Pixie',
    "classes": ['mage'],
    'lanes': ['damage', 'roam'],
    'roles': ['mobility', 'harass'],
    'tier': 'c',
    'tier_index': 5,
    "folder": 'krixi'
  },
  {
    "name": 'Lauriel',
    'alt_names': ['Lauriel', 'laurel'],
    "nickname": 'Archangel',
    "classes": ['mage', 'assassin'],
    'lanes': ['mid', 'roam'],
    'roles': ['mobility'],
    'tier': 's',
    'tier_index': 2,
    "folder": 'lauriel'
  },
  {
    "name": 'Liliana',
    'alt_names': ['Liliana', 'lil', 'lilliana'],
    "nickname": 'Elegant',
    "classes": ['mage', 'assassin'],
    'lanes': ['mid', 'roam'],
    'roles': ['mobility', 'finisher'],
    'tier': 's',
    'tier_index': 2,
    "folder": 'liliana'
  },
  {
    "name": 'Lindis',
    'alt_names': ['Lindis'],
    "nickname": 'Sentinel',
    "classes": ['marksman'],
    'lanes': ['damage', 'jungle'],
    'roles': ['initiator', 'finisher'],
    'tier': 'b',
    'tier_index': 4,
    "folder": 'lindis'
  },
  {
    "name": 'Lu Bu',
    'alt_names': ['Lu Bu', 'lubu'],
    "nickname": 'Great Warlord',
    "classes": ['warrior'],
    'lanes': ['ds', 'solo', 'jungle'],
    'roles': ['life steal'],
    'tier': 'a',
    'tier_index': 3,
    "folder": 'lubu'
  },
  {
    "name": 'Lumburr',
    'alt_names': ['Lumburr', 'lumbur'],
    "nickname": 'Elemental',
    "classes": ['support', 'tank'],
    'lanes': ['support', 'roam'],
    'roles': ['control', 'buffs'],
    'tier': 'b',
    'tier_index': 4,
    "folder": 'lumburr'
  },
  {
    "name": 'Maloch',
    'alt_names': ['Maloch', 'maloc', 'malock'],
    "nickname": 'Merciless',
    "classes": ['warrior', 'tank'],
    'lanes': ['solo', 'roam', 'ds'],
    'roles': ['finisher', 'life steal'],
    'tier': 's',
    'tier_index': 2,
    "folder": 'maloch'
  },
  {
    "name": 'Max',
    'alt_names': ['Max'],
    "nickname": 'Wunderkind',
    "classes": ['tank', 'warrior'],
    'lanes': ['solo', 'ds', 'roam'],
    'roles': ['mobility', 'initiator', 'finisher'],
    'tier': 'b',
    'tier_index': 4,
    "folder": 'max'
  },
  {
    "name": 'Mganga',
    'alt_names': ['Mganga', 'mgangster', 'ganga'],
    "nickname": 'Unspeakable',
    "classes": ['mage', 'support'],
    'lanes': ['mid', 'roam'],
    'roles': ['harass', 'healer', 'life steal'],
    'tier': 'c',
    'tier_index': 5,
    "folder": 'mganga'
  },
  {
    "name": 'Mina',
    'alt_names': ['Mina'],
    "nickname": 'Reaper Queen',
    "classes": ['tank'],
    'lanes': ['support', 'roam'],
    'roles': ['control'],
    'tier': 'b',
    'tier_index': 4,
    "folder": 'mina'
  },
  {
    "name": 'Moren',
    'alt_names': ['Moren'],
    "nickname": 'Technowiz',
    "classes": ['marksman'],
    'lanes': ['damage', 'jungle'],
    'roles': ['mobility', 'jungle'],
    'tier': 'b',
    'tier_index': 4,
    "folder": 'moren'
  },
  {
    "name": 'Murad',
    'alt_names': ['Murad'],
    "nickname": 'Wanderer',
    "classes": ['assassin'],
    'lanes': ['jungle'],
    'roles': ['mobility'],
    'tier': 'ss',
    'tier_index': 1,
    "folder": 'murad'
  },
  {
    "name": 'Nakroth',
    'alt_names': ['Nakroth', 'nak'],
    "nickname": "Executioner's Blade",
    "classes": ['assassin'],
    'lanes': ['jungle'],
    'roles': ['mobility'],
    'tier': 'b',
    'tier_index': 4,
    "folder": 'nakroth'
  },
  {
    "name": 'Natalya',
    'alt_names': ['Natalya', 'nat'],
    "nickname": 'Nether Queen',
    "classes": ['mage'],
    'lanes': ['mid', 'damage', 'roam'],
    'roles': ['harass'],
    'tier': 'b',
    'tier_index': 4,
    "folder": 'natalya'
  },
  {
    "name": 'Omega',
    'alt_names': ['Omega'],
    "nickname": 'Awoken Mech',
    "classes": ['tank'],
    'lanes': ['ds', 'solo', 'roam'],
    'roles': ['control'],
    'tier': 'd',
    'tier_index': 6,
    "folder": 'omega'
  },
  {
    "name": 'Omen',
    'alt_names': ['Omen'],
    "nickname": 'Insatiable',
    "classes": ['warrior'],
    'lanes': ['ds', 'solo', 'jungle'],
    'roles': ['mobility'],
    'tier': 'a',
    'tier_index': 3,
    "folder": 'omen'
  },
  {
    "name": 'Ormarr',
    'alt_names': ['Ormarr', 'ormar', 'omar'],
    "nickname": 'Frenzy',
    "classes": ['tank', 'warrior'],
    'lanes': ['roam', 'support'],
    'roles': ['control', 'mobility'],
    'tier': 'a',
    'tier_index': 3,
    "folder": 'ormarr'
  },
  {
    "name": 'Peura',
    'alt_names': ['Peura', 'pura'],
    "nickname": 'Guardian of the Glade',
    "classes": ['support'],
    'lanes': ['support', 'roam'],
    'roles': ['buffs'],
    'tier': 'b',
    'tier_index': 4,
    "folder": 'peura'
  },
  {
    "name": 'Preyta',
    'alt_names': ['Preyta'],
    "nickname": 'Illest',
    "classes": ['mage'],
    'lanes': ['mid', 'roam'],
    'roles': ['harass'],
    'tier': 'a',
    'tier_index': 3,
    "folder": 'preyta'
  },
  {
    "name": 'Raz',
    'alt_names': ['Raz'],
    "nickname": 'Fist',
    "classes": ['mage', 'assassin'],
    'lanes': ['mid', 'solo', 'roam'],
    'roles': ['harass'],
    'tier': 's',
    'tier_index': 2,
    "folder": 'raz'
  },
  {
    "name": 'Ryoma',
    'alt_names': ['Ryoma', 'rioma'],
    "nickname": 'Ronin',
    "classes": ['warrior'],
    'lanes': ['ds', 'jungle'],
    'roles': ['harass', 'finisher'],
    'tier': 'ss',
    'tier_index': 1,
    "folder": 'ryoma'
  },
  {
    "name": 'Skud',
    'alt_names': ['Skud'],
    "nickname": 'Smasher',
    "classes": ['warrior', 'tank'],
    'lanes': ['support', 'ds', 'solo'],
    'roles': ['mobility', 'control'],
    'tier': 'b',
    'tier_index': 4,
    "folder": 'skud'
  },
  {
    "name": 'Slimz',
    'alt_names': ['Slimz', 'slims'],
    "nickname": 'Trustworthy',
    "classes": ['marksman'],
    'lanes': ['solo', 'jungle', 'damage'],
    'roles': ['mobility', 'initiator'],
    'tier': 'b',
    'tier_index': 4,
    "folder": 'slimz'
  },
  {
    "name": 'Superman',
    'alt_names': ['Superman', 'super', 'sm'],
    "nickname": 'Man of Steel',
    "classes": ['warrior', 'tank'],
    'lanes': ['roam', 'ds'],
    'roles': ['mobility', 'initiator'],
    'tier': 'ss',
    'tier_index': 1,
    "folder": 'superman'
  },
  {
    "name": 'Taara',
    'alt_names': ['Taara', 'tara'],
    "nickname": 'War Hammer',
    "classes": ['tank', 'warrior'],
    'lanes': [],
    'roles': ['mobility', 'healer', 'life steal'],
    'tier': 'c',
    'tier_index': 5,
    "folder": 'taara'
  },
  {
    "name": 'TeeMee',
    'alt_names': ['TeeMee', 'tee'],
    "nickname": 'Stalwart Twins',
    "classes": ['support', 'tank'],
    'lanes': ['support', 'roam'],
    'roles': ['initiator', 'mobility'],
    'tier': 's',
    'tier_index': 2,
    "folder": 'teemee'
  },
  {
    "name": "Tel'Annas",
    'alt_names': ["Tel'Annas", 'tel', 'telannas', 'telanas'],
    "nickname": 'Ageless',
    "classes": ['marksman'],
    'lanes': ['roam', 'damage'],
    'roles': ['finisher'],
    'tier': 'a',
    'tier_index': 3,
    "folder": 'telannas'
  },
  {
    "name": 'Thane',
    'alt_names': ['Thane'],
    "nickname": 'Protector',
    "classes": ['tank', 'warrior'],
    'lanes': ['support', 'roam'],
    'roles': ['control', 'initiator'],
    'tier': 'a',
    'tier_index': 3,
    "folder": 'thane'
  },
  {
    "name": 'Flash',
    'alt_names': ['Flash'],
    "nickname": 'Fastest Man Alive',
    "classes": ['mage', 'assassin'],
    'lanes': ['roam', 'mid', 'solo'],
    'roles': ['mobility', 'initiator'],
    'tier': 'a',
    'tier_index': 3,
    "folder": 'flash'
  },
  {
    "name": 'Joker',
    'alt_names': ['Joker'],
    "nickname": 'Clown Prince of Crime',
    "classes": ['marksman'],
    'lanes': ['mid', 'jungle'],
    'roles': ['harass'],
    'tier': 'a',
    'tier_index': 3,
    "folder": 'joker'
  },
  {
    "name": 'Toro',
    'alt_names': ['Toro'],
    "nickname": '',
    "classes": ['tank'],
    'lanes': ['ds', 'solo'],
    'roles': ['control', 'initiator'],
    'tier': 'd',
    'tier_index': 6,
    "folder": 'toro'
  },
  {
    "name": 'Valhein',
    'alt_names': ['Valhein', 'val'],
    "nickname": 'Demon Hunter',
    "classes": ['marksman'],
    'lanes': ['damage'],
    'roles': ['harass'],
    'tier': 'd',
    'tier_index': 6,
    "folder": 'valhein'
  },
  {
    "name": 'Veera',
    'alt_names': ['Veera', 'vera'],
    "nickname": 'Soul Harvester',
    "classes": ['mage'],
    'lanes': ['damage', 'roam'],
    'roles': ['initiator'],
    'tier': 'd',
    'tier_index': 6,
    "folder": 'veera'
  },
  {
    "name": 'Violet',
    'alt_names': ['Violet', 'vio'],
    "nickname": 'Pistol Assassin',
    "classes": ['marksman'],
    'lanes': ['solo', 'jungle'],
    'roles': ['mobility', 'finisher'],
    'tier': 'ss',
    'tier_index': 1,
    "folder": 'violet'
  },
  {
    "name": 'Wisp',
    'alt_names': ['Wisp'],
    "nickname": 'Mischievous',
    "classes": ['marksman'],
    'lanes': ['damage', 'jungle'],
    'roles': [],
    'tier': 'b',
    'tier_index': 4,
    "folder": 'wisp'
  },
  {
    "name": 'Wonder Woman',
    'alt_names': ['Wonder Woman', 'wonderwoman', 'ww', 'wonder'],
    "nickname": 'Amazon of Themyscira',
    "classes": ['warrior'],
    'lanes': ['solo', 'ds', 'roam'],
    'roles': ['control'],
    'tier': 'a',
    'tier_index': 3,
    "folder": 'wonderwoman'
  },
  {
    "name": 'Wukong',
    'alt_names': ['Wukong', 'monkey'],
    "nickname": 'Monkey King',
    "classes": ['assassin', 'warrior'],
    'lanes': ['jungle'],
    'roles': ['mobility'],
    'tier': 'a',
    'tier_index': 3,
    "folder": 'wukong'
  },
  {
    "name": 'Xeniel',
    'alt_names': ['Xeniel', 'xenel', 'x'],
    "nickname": 'Immaculate',
    "classes": ['tank', 'support'],
    'lanes': ['ds', 'solo'],
    'roles': ['control', 'healer'],
    'tier': 'a',
    'tier_index': 3,
    "folder": 'xeniel'
  },
  {
    "name": 'Yorn',
    'alt_names': ['Yorn'],
    "nickname": 'Hotshot',
    "classes": ['marskman'],
    'lanes': ['damage', 'mid'],
    'roles': ['harass'],
    'tier': 'b',
    'tier_index': 4,
    "folder": 'yorn'
  },
  {
    "name": 'Zanis',
    'alt_names': ['Zanis'],
    "nickname": 'Dragoon',
    "classes": ['warrior'],
    'lanes': ['jungle', 'roam'],
    'roles': ['finisher'],
    'tier': 'c',
    'tier_index': 5,
    "folder": 'zanis'
  },
  {
    "name": 'Zephys',
    'alt_names': ['Zephys', 'zephis'],
    "nickname": 'Doomspear',
    "classes": ['warrior', 'assassin'],
    'lanes': ['jungle', 'roam'],
    'roles': ['mobility'],
    'tier': 's',
    'tier_index': 2,
    "folder": 'zephys'
  },
  {
    "name": 'Zill',
    'alt_names': ['Zill'],
    "nickname": 'Tempest',
    "classes": ['mage', 'assassin'],
    'lanes': [],
    'roles': ['mobility'],
    'tier': 'a',
    'tier_index': 3,
    "folder": 'zill'
  },
  {
    "name": 'Zuka',
    'alt_names': ['Zuka'],
    "nickname": 'Pandharma Master',
    "classes": ['warrior', 'assassin'],
    'lanes': ['jungle', 'solo', 'ds'],
    'roles': ['mobility'],
    'tier': 'a',
    'tier_index': 3,
    "folder": 'zuka'
  }
]

export default HEROES
